var Enum = require('enum');

/* Captured from:
    https://www.tivo.com/assets/images/abouttivo/resources/downloads/brochures/TiVo_TCP_Network_Remote_Control_Protocol.pdf
*/

var TivoIrCode = new Enum([
	'UP',
	'DOWN',
	'LEFT',
	'RIGHT',
	'SELECT',
	'TIVO',
	'LIVETV',
	'GUIDE',
	'INFO',
	'EXIT ',
	'THUMBSUP',
	'THUMBSDOWN',
	'CHANNELUP',
	'CHANNELDOWN',
	'MUTE',
	'VOLUMEDOWN',
	'VOLUMEUP',
	'TVINPUT',
	'VIDEO_MODE_FIXED_480i ',
	'VIDEO_MODE_FIXED_480p',
	'VIDEO_MODE_FIXED_720p',
	'VIDEO_MODE_FIXED_1080i ',
	'VIDEO_MODE_HYBRID ',
	'VIDEO_MODE_HYBRID_720p ',
	'VIDEO_MODE_HYBRID_1080i ',
	'VIDEO_MODE_NATIVE ',
	'CC_ON ',
	'CC_OFF',
	'OPTIONS',
	'ASPECT_CORRECTION_FULL ',
	'ASPECT_CORRECTION_PANEL ',
	'ASPECT_CORRECTION_ZOOM ',
	'ASPECT_CORRECTION_WIDE_ZOOM ',
	'PLAY',
	'FORWARD',
	'REVERSE',
	'PAUSE',
	'SLOW',
	'REPLAY',
	'ADVANCE',
	'RECORD',
	'NUM0',
	'NUM1',
	'NUM2',
	'NUM3',
	'NUM4',
	'NUM5',
	'NUM6',
	'NUM7',
	'NUM8',
	'NUM9',
	'ENTER',
	'CLEAR',
	'ACTION_A',
	'ACTION_B',
	'ACTION_C',
	'ACTION_D'
]);

exports.TivoIrCode = TivoIrCode;